/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type {
  RocketNodeDistributorFactory,
  RocketNodeDistributorFactoryInterface,
} from '../RocketNodeDistributorFactory';

const _abi = [
  {
    inputs: [
      {
        internalType: 'contract RocketStorageInterface',
        name: '_rocketStorageAddress',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: '_address',
        type: 'address',
      },
    ],
    name: 'ProxyCreated',
    type: 'event',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_nodeAddress',
        type: 'address',
      },
    ],
    name: 'createProxy',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_nodeAddress',
        type: 'address',
      },
    ],
    name: 'getProxyAddress',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getProxyBytecode',
    outputs: [
      {
        internalType: 'bytes',
        name: '',
        type: 'bytes',
      },
    ],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [],
    name: 'version',
    outputs: [
      {
        internalType: 'uint8',
        name: '',
        type: 'uint8',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];

export class RocketNodeDistributorFactory__factory {
  static readonly abi = _abi;
  static createInterface(): RocketNodeDistributorFactoryInterface {
    return new utils.Interface(_abi) as RocketNodeDistributorFactoryInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): RocketNodeDistributorFactory {
    return new Contract(address, _abi, signerOrProvider) as RocketNodeDistributorFactory;
  }
}
