/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { RocketClaimNode, RocketClaimNodeInterface } from '../RocketClaimNode';

const _abi = [
  {
    inputs: [
      {
        internalType: 'contract RocketStorageInterface',
        name: '_rocketStorageAddress',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [],
    name: 'claim',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_nodeAddress',
        type: 'address',
      },
    ],
    name: 'getClaimPossible',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_nodeAddress',
        type: 'address',
      },
    ],
    name: 'getClaimRewardsAmount',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_nodeAddress',
        type: 'address',
      },
    ],
    name: 'getClaimRewardsPerc',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getEnabled',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_nodeAddress',
        type: 'address',
      },
      {
        internalType: 'bool',
        name: '_enable',
        type: 'bool',
      },
    ],
    name: 'register',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'version',
    outputs: [
      {
        internalType: 'uint8',
        name: '',
        type: 'uint8',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];

export class RocketClaimNode__factory {
  static readonly abi = _abi;
  static createInterface(): RocketClaimNodeInterface {
    return new utils.Interface(_abi) as RocketClaimNodeInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): RocketClaimNode {
    return new Contract(address, _abi, signerOrProvider) as RocketClaimNode;
  }
}
